from __future__ import annotations
from typing import Protocol
from core.types import DocumentChunk, RetrievalResult


class VectorStore(Protocol):
    def upsert(self, chunks: list[DocumentChunk], embeddings: list[list[float]], source: str) -> int: ...
    def query(self, embedding: list[float], top_k: int, threshold: float | None = None) -> list[RetrievalResult]: ...
    def delete_source(self, source: str) -> None: ...
    def reset(self) -> None: ...
    def stats(self) -> dict: ...
